/**Copyright (C) 2013 Thomas Maher
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */

package com.jimsuplee.fighterjets;

import android.app.ListActivity;
//import android.app.Activity;
import android.content.Intent;
import android.widget.ListView;
import android.widget.ArrayAdapter;
import java.util.ArrayList;
import java.util.List;
import android.os.Bundle;
//import android.widget.ArrayAdapter;
import android.net.Uri;
import android.widget.TextView;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.view.View;
//import android.util.Log;

public class Fighter extends ListActivity {
	static final String TAG = "FIGHTERJETS";
	
	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
	    displayListView();
	}
	
    private void displayListView() {
        //////Log.w(TAG, "In Flight.displayListView(), about to make carrierList");
        List<String> fighterList = new ArrayList<String>();
        //fighterList.add("ACAZ C.2 2 seat fighter");
        //fighterList.add("Adamoli-Cattani fighter");
        //fighterList.add("AD Scout");
        fighterList.add("ACAZ C.2 2 seat fighter");
        fighterList.add("Adamoli-Cattani fighter");
        fighterList.add("AD Scout");
        fighterList.add("ADA/HAL Advanced Medium Combat Aircraft");
        fighterList.add("AEG D.I, D.II & D.III");
        fighterList.add("AEG Dr.I triplane");
        fighterList.add("Aerfer Ariete");
        fighterList.add("Aerfer Sagittario 2 lightweight fighter");
        fighterList.add("Aero Ae 02");
        fighterList.add("Aero Ae 04");
        fighterList.add("Aero A.18");
        fighterList.add("Aero A.19");
        fighterList.add("Aero A.20");
        fighterList.add("Aero A.102");
        fighterList.add("Aeromarine PG-1");
        fighterList.add("Aeronautica Umbra Trojani AUT.18");
        fighterList.add("AIDC F-CK-1 Ching-kuo");
        fighterList.add("Airco DH.1");
        fighterList.add("Airco DH.2");
        fighterList.add("Airco DH.5");
        fighterList.add("Albatros D.I");
        fighterList.add("Albatros D.II");
        fighterList.add("Albatros D.III");
        fighterList.add("Albatros D.IV");
        fighterList.add("Albatros D.V & D.Va");
        fighterList.add("Albatros D.VI pusher fighter");
        fighterList.add("Albatros D.VII");
        fighterList.add("Albatros D.IX");
        fighterList.add("Albatros D.X");
        fighterList.add("Albatros D.XI");
        fighterList.add("Albatros D.XII");
        fighterList.add("Albatros Dr.I triplane");
        fighterList.add("Albatros Dr.II triplane");
        fighterList.add("Albatros L 65 two-seat reconnaissance fighter");
        fighterList.add("Albatros L 77v reconnaissance/fighter");
        fighterList.add("Albatros L 84");
        fighterList.add("Albatros W.4 fighter floatplane");
        fighterList.add("Albree Pigeon-Fraser Pursuit");
        fighterList.add("Alcock Scout");
        fighterList.add("Alekseyev I-211 & 215");
        fighterList.add("Alter A.1");
        fighterList.add("Ambrosini SAI.107 & 207");
        fighterList.add("Ambrosini SAI.403");
        fighterList.add("Ambrosini SS.4");
        fighterList.add("Amiot 110 lightweight Jockey fighter");
        fighterList.add("Anatra Anadis");
        fighterList.add("ANF Les Mureaux 114 night fighter");
        fighterList.add("ANF Les Mureaux 170");
        fighterList.add("ANF Les Mureaux 180 2 seat fighter");
        fighterList.add("ANF Les Mureaux 190");
        fighterList.add("Ansaldo A.1 Balilla");
        fighterList.add("Ansaldo ISVA floatplane fighter");
        fighterList.add("Ansaldo SVA");
        fighterList.add("Arado SD I");
        fighterList.add("Arado SD II");
        fighterList.add("Arado SD III");
        fighterList.add("Arado SSD I");
        fighterList.add("Arado Ar 64");
        fighterList.add("Arado Ar 65");
        fighterList.add("Arado Ar 67");
        fighterList.add("Arado Ar 68");
        fighterList.add("Arado Ar 76 lightweight fighter");
        fighterList.add("Arado Ar 80");
        fighterList.add("Arado Ar 197");
        fighterList.add("Arado Ar 240");
        fighterList.add("Arado Ar 440");
        fighterList.add("Armstrong Whitworth Ara");
        fighterList.add("Armstrong Whitworth Armadillo");
        fighterList.add("Armstrong Whitworth A.W.16");
        fighterList.add("Armstrong Whitworth F.K.6 heavy fighter");
        fighterList.add("Armstrong Whitworth F.K.9 & 10");
        fighterList.add("Armstrong Whitworth Siskin");
        fighterList.add("Armstrong Whitworth Starling");
        fighterList.add("Armstrong Whitworth AW.35 Scimitar");
        fighterList.add("Army Arsenal Model 3");
        fighterList.add("Arsenal-Delanne 10");
        fighterList.add("Arsenal VG-30 - 39");
        fighterList.add("Arsenal VB 10");
        fighterList.add("Arsenal VG 90 carrier fighter");
        fighterList.add("Atlas Cheetah");
        fighterList.add("Austin-Ball A.F.B.1");
        fighterList.add("Austin Osprey");
        fighterList.add("Austin Greyhound");
        fighterList.add("Avia BH-3");
        fighterList.add("Avia BH-4");
        fighterList.add("Avia BH-6");
        fighterList.add("Avia BH-7");
        fighterList.add("Avia BH-8");
        fighterList.add("Avia BH-17");
        fighterList.add("Avia BH-19");
        fighterList.add("Avia BH-21");
        fighterList.add("Avia BH-23 night fighter");
        fighterList.add("Avia BH-33");
        fighterList.add("Avia B-34");
        fighterList.add("Avia B-534");
        fighterList.add("Avia B-634");
        fighterList.add("Avia B-35");
        fighterList.add("Avia B-135");
        fighterList.add("Avia S-199");
        fighterList.add("Aviatik D.I");
        fighterList.add("Aviatik (Berg) D.II");
        fighterList.add("Aviatik D.III");
        fighterList.add("Aviatik D.VI");
        fighterList.add("Aviatik D.VII");
        fighterList.add("Aviméta 88 2 seat night fighter/reconnaissance");
        fighterList.add("Aviotehas PN-3");
        fighterList.add("AVIS I");
        fighterList.add("AVIS II");
        fighterList.add("AVIS III");
        fighterList.add("AVIS IV");
        fighterList.add("Avro 523 Pike Zeppelin fighter");
        fighterList.add("Avro 527");
        fighterList.add("Avro 530 2 seat fighter");
        fighterList.add("Avro 531 Spider");
        fighterList.add("Avro 566 Avenger");
        fighterList.add("Avro 584 Avocet");
        fighterList.add("Avro Canada CF-100 Canuck");
        fighterList.add("Avro Canada CF-105 Arrow");
        fighterList.add("Bachem Ba 349 rocket VTO interceptor");
        fighterList.add("BAJ IV 2 seat fighter");
        fighterList.add("BAT Bantam");
        fighterList.add("BAT Basilisk");
        fighterList.add("Beardmore W.B.2");
        fighterList.add("Beardmore W.B.III");
        fighterList.add("Beardmore W.B.IV");
        fighterList.add("Beardmore W.B.V");
        fighterList.add("Beardmore W.B.XXVI two seat fighter");
        fighterList.add("Bell YFM-1 Airacuda bomber destroyer");
        fighterList.add("Bell XFL Airabonita naval fighter");
        fighterList.add("Bell P-39 Airacobra");
        fighterList.add("Bell P-59 Airacomet");
        fighterList.add("Bell P-63 Kingcobra");
        fighterList.add("Bell XP-77 lightweight fighter");
        fighterList.add("Bell XP-83");
        fighterList.add("Berckmans Speed Scout");
        fighterList.add("Bereznyak-Isayev BI-1 rocket fighter");
        fighterList.add("Berliner-Joyce XFJ");
        fighterList.add("Berliner-Joyce F2J");
        fighterList.add("Berliner-Joyce XF3J");
        fighterList.add("Berliner-Joyce P-16");
        fighterList.add("Bernard SIMB AB 10");
        fighterList.add("Bernard SIMB AB 12");
        fighterList.add("Bernard SIMB AB 14");
        fighterList.add("Bernard 15");
        fighterList.add("Bernard 20");
        fighterList.add("Bernard H.52 floatplane fighter");
        fighterList.add("Bernard 74 & 75");
        fighterList.add("Bernard H 110 floatplane fighter");
        fighterList.add("Bernard 260");
        fighterList.add("Bisnovat SK-2");
        fighterList.add("Blackburn F.3");
        fighterList.add("Blackburn Firebrand torpedo fighter");
        fighterList.add("Blackburn Lincock");
        fighterList.add("Blackburn Roc turret fighter");
        fighterList.add("Blackburn Skua dive bomber/fighter");
        fighterList.add("Blackburn Triplane Zeppelin fighter");
        fighterList.add("Blackburn Turcock");
        fighterList.add("Blériot-SPAD S.41");
        fighterList.add("Blériot-SPAD S.51");
        fighterList.add("Blériot-SPAD S.60 two-seat fighter");
        fighterList.add("Blériot-SPAD S.61");
        fighterList.add("Blériot-SPAD S.71 & 72");
        fighterList.add("Blériot-SPAD S.81");
        fighterList.add("Blériot-SPAD S.91");
        fighterList.add("Blériot-SPAD S.510");
        fighterList.add("Blériot-SPAD S.710");
        fighterList.add("Bloch MB.150-157");
        fighterList.add("Blohm & Voss BV 40");
        fighterList.add("Blohm & Voss BV 155");
        fighterList.add("Boeing FB");
        fighterList.add("Boeing F2B");
        fighterList.add("Boeing F3B");
        fighterList.add("Boeing F4B");
        fighterList.add("Boeing XF5B");
        fighterList.add("Boeing XF6B");
        fighterList.add("Boeing XF7B");
        fighterList.add("Boeing XF8B");
        fighterList.add("Boeing PW-9");
        fighterList.add("Boeing XP-4");
        fighterList.add("Boeing XP-7");
        fighterList.add("Boeing XP-8");
        fighterList.add("Boeing XP-9");
        fighterList.add("Boeing P-12");
        fighterList.add("Boeing XP-15");
        fighterList.add("Boeing P-26 Peashooter");
        fighterList.add("Boeing P-29");
        fighterList.add("Boeing Model 100");
        fighterList.add("Boeing Model 218");
        fighterList.add("Boeing Model 256");
        fighterList.add("Boeing Model 267");
        fighterList.add("Boeing F/A-18E/F Super Hornet");
        fighterList.add("Boeing X-32");
        fighterList.add("Bolkhovitinov I-1");
        fighterList.add("Borel C.2 2 seat fighter");
        fighterList.add("Borovkov-Florov I-207");
        fighterList.add("Boulton & Paul Bobolink");
        fighterList.add("Boulton Paul Defiant turret fighter");
        fighterList.add("Boulton & Paul Partridge");
        fighterList.add("Breda Ba.27");
        fighterList.add("Breguet BUC/BLC escort fighter");
        fighterList.add("Breguet LE Laboratoire Eiffel");
        fighterList.add("Breguet Taon strike fighter");
        fighterList.add("Breguet 17 night fighter");
        fighterList.add("Brewster F2A Buffalo");
        fighterList.add("Bristol Badger");
        fighterList.add("Bristol Bagshot home defence fighter");
        fighterList.add("Bristol Beaufighter strike fighter");
        fighterList.add("Bristol Blenheim night fighter");
        fighterList.add("Bristol Bulldog");
        fighterList.add("Bristol Bullfinch");
        fighterList.add("Bristol Bullpup");
        fighterList.add("Bristol F.2 Fighter 2 seat fighter");
        fighterList.add("Bristol Jupiter Fighter");
        fighterList.add("Bristol M.1 Bullet");
        fighterList.add("Bristol Scout");
        fighterList.add("Bristol Scout F");
        fighterList.add("Bristol T.T.A. home defence fighter");
        fighterList.add("Bristol Type 101 two-seat fighter");
        fighterList.add("Bristol Type 123");
        fighterList.add("Bristol Type 133");
        fighterList.add("Bristol Type 146");
        fighterList.add("British Aerospace Sea Harrier V/STOL fighter");
        fighterList.add("Burgess HT-B/HT-2 speed scout");
        fighterList.add("Buscaylet-Bechereau BB.2");
        fighterList.add("Buscaylet-de Monge 5/2");
        fighterList.add("CAC Boomerang");
        fighterList.add("CAC CA-15 Kangaroo");
        fighterList.add("CAC Wirraway trainer/emergency fighter");
        fighterList.add("Canadian Car and Foundry FDB-1");
        fighterList.add("Caproni Ca.20");
        fighterList.add("Caproni Ca.70 & 71 night fighter");
        fighterList.add("Caproni Ca.114");
        fighterList.add("Caproni Ca.165");
        fighterList.add("Caproni Ca.301");
        fighterList.add("Caproni Ca.331");
        fighterList.add("Caproni Ca.335");
        fighterList.add("Caproni CH.1");
        fighterList.add("Caproni Vizzola F.4");
        fighterList.add("Caproni Vizzola F.5");
        fighterList.add("Caproni Vizzola F.6");
        fighterList.add("Caudron O");
        fighterList.add("Caudron C.714");
        fighterList.add("Caudron-Renault CR.760");
        fighterList.add("Caudron-Renault CR.770");
        fighterList.add("Chengdu FC-1 Xiaolong/PAC JF-17 Thunder");
        fighterList.add("Chengdu J-7");
        fighterList.add("Chengdu J-10");
        fighterList.add("Chengdu J-20");
        fighterList.add("Christmas Bullet");
        fighterList.add("Chu X-PO");
        fighterList.add("Comte AC-1");
        fighterList.add("Consolidated PB-2/P-30 2 seat fighter");
        fighterList.add("Consolidated Vultee XP-81 mixed propulsion fighter");
        fighterList.add("Convair XF-92");
        fighterList.add("Convair F-102 Delta Dagger interceptor");
        fighterList.add("Convair F-106 Delta Dart interceptor");
        fighterList.add("Convair XFY Pogo VTOL turboprop fighter");
        fighterList.add("Convair F2Y Sea Dart seaplane jet fighter");
        fighterList.add("Courtois-Suffit Lescop CSL-1");
        fighterList.add("Curtiss 18");
        fighterList.add("Curtiss HA floatplane fighter");
        fighterList.add("Curtiss TS-1 and F4C-1");
        fighterList.add("Curtiss BF2C Goshawk bomber-fighter");
        fighterList.add("Curtiss F6C Hawk");
        fighterList.add("Curtiss F7C Seahawk");
        fighterList.add("Curtiss F8C Falcon/Helldiver 2 seat fighter-bomber");
        fighterList.add("Curtiss F9C Sparrowhawk parasite fighter");
        fighterList.add("Curtiss XF10C Helldiver 2 seat fighter-bomber");
        fighterList.add("Curtiss F11C Goshawk");
        fighterList.add("Curtiss F12C parasol fighter");
        fighterList.add("Curtiss XF13C");
        fighterList.add("Curtiss XF14C");
        fighterList.add("Curtiss XF15C mixed-propulsion fighter");
        fighterList.add("Curtiss PW-8");
        fighterList.add("Curtiss P-1 Hawk");
        fighterList.add("Curtiss P-2 Hawk");
        fighterList.add("Curtiss P-3 Hawk/XP-21");
        fighterList.add("Curtiss P-5 Superhawk");
        fighterList.add("Curtiss P-6 Hawk");
        fighterList.add("Curtiss XP-10");
        fighterList.add("Curtiss YP-20");
        fighterList.add("Curtiss XP-31 Swift");
        fighterList.add("Curtiss P-36 Hawk");
        fighterList.add("Curtiss XP-37");
        fighterList.add("Curtiss P-40 Warhawk");
        fighterList.add("Curtiss XP-46");
        fighterList.add("Curtiss XP-53 & P-60");
        fighterList.add("Curtiss XP-62");
        fighterList.add("Curtiss-Wright CW-21 lightweight fighter");
        fighterList.add("Curtiss-Wright XP-55 Ascender");
        fighterList.add("Curtiss-Wright XF-87 Blackhawk");
        fighterList.add("Daimler D.I");
        fighterList.add("Dassault Balzac V");
        fighterList.add("Dassault Étendard II");
        fighterList.add("Dassault Étendard IV");
        fighterList.add("Dassault Étendard VI");
        fighterList.add("Dassault Mirage III");
        fighterList.add("Dassault Mirage IIIV VTOL fighter");
        fighterList.add("Dassault Mirage 5 & 50");
        fighterList.add("Dassault Mirage 2000");
        fighterList.add("Dassault Mirage 4000");
        fighterList.add("Dassault Mirage F1");
        fighterList.add("Dassault Mirage F2");
        fighterList.add("Dassault Mirage G");
        fighterList.add("Dassault Mystère");
        fighterList.add("Dassault Mystère IV");
        fighterList.add("Dassault Ouragan");
        fighterList.add("Dassault Rafale");
        fighterList.add("Dassault Super Mystère fighter-bomber");
        fighterList.add("Dassault-Breguet Super Étendard strike fighter");
        fighterList.add("Dayton-Wright XPS-1");
        fighterList.add("de Bruyère C.1 canard pusher");
        fighterList.add("de Havilland Dormouse");
        fighterList.add("de Havilland DH.77");
        fighterList.add("de Havilland Hornet/Sea Hornet");
        fighterList.add("de Havilland Mosquito");
        fighterList.add("de Havilland Sea Venom");
        fighterList.add("de Havilland DH.110 Sea Vixen");
        fighterList.add("de Havilland Vampire/Sea Vampire");
        fighterList.add("de Havilland Venom");
        fighterList.add("De Marçay 2");
        fighterList.add("De Marçay 4");
        fighterList.add("de Monge M-101 2 seat fighter");
        fighterList.add("Descamps 27");
        fighterList.add("Dewoitine D.1");
        fighterList.add("Dewoitine D.8");
        fighterList.add("Dewoitine D.9");
        fighterList.add("Dewoitine D.15");
        fighterList.add("Dewoitine D.19");
        fighterList.add("Dewoitine D.12");
        fighterList.add("Dewoitine D.21 & D.53");
        fighterList.add("Dewoitine D.25 2 seat fighter");
        fighterList.add("Dewoitine D.27");
        fighterList.add("Dewoitine D.371");
        fighterList.add("Dewoitine D.500 & D.501");
        fighterList.add("Dewoitine D.510");
        fighterList.add("Dewoitine D.503/D.511");
        fighterList.add("Dewoitine D.513 & 514");
        fighterList.add("Dewoitine D.520");
        fighterList.add("Dewoitine D.521");
        fighterList.add("Dewoitine D.535");
        fighterList.add("Dewoitine D.560 & D.570");
        fighterList.add("DFW Floh (Flea)");
        fighterList.add("Díaz Type C");
        fighterList.add("Dobi-III");
        fighterList.add("Doflug D-3802");
        fighterList.add("Doflug D-3803");
        fighterList.add("Dornier Do H");
        fighterList.add("Dornier Do 10 two seat fighter");
        fighterList.add("Dornier Do 17 night fighter");
        fighterList.add("Dornier Do 215 night fighter");
        fighterList.add("Dornier Do 217 night fighter");
        fighterList.add("Dornier Do 335");
        fighterList.add("Douglas P-70 Havoc night fighter");
        fighterList.add("Douglas XA-26A night fighter");
        fighterList.add("Douglas XFD");
        fighterList.add("Douglas F3D Skyknight");
        fighterList.add("Douglas F4D Skyray");
        fighterList.add("Douglas F5D Skylancer");
        fighterList.add("Ducrot SLD");
        fighterList.add("Dufaux avions-canon");
        fighterList.add("Dufaux C.1");
        fighterList.add("Eberhart XFG & XF2G");
        fighterList.add("EFW N-20");
        fighterList.add("ENAER Pantera");
        fighterList.add("Engels MI");
        fighterList.add("Engineering Division PW-1");
        fighterList.add("Engineering Division TP-1 two seat fighter");
        fighterList.add("English Electric Lightning");
        fighterList.add("Euler D.I");
        fighterList.add("Euler D.II");
        fighterList.add("Euler Dr.I, II & III");
        fighterList.add("Euler Gelber Hund");
        fighterList.add("Euler Vierdecker quadruplane");
        fighterList.add("Euler Versuchszweisitzer 2 seat fighter");
        fighterList.add("Eurofighter Typhoon");
        fighterList.add("Fairey F.2 3 seat long range fighter");
        fighterList.add("Fairey Fantôme");
        fighterList.add("Fairey Fleetwing fleet fighter");
        fighterList.add("Fairey Flycatcher");
        fighterList.add("Fairey Firefly monoplane fleet fighter");
        fighterList.add("Fairey Firefly II biplane");
        fighterList.add("Fairey Fox Belgian fighter/reconsaissance");
        fighterList.add("Fairey Fulmar fleet fighter");
        fighterList.add("Fairey Hamble Baby floatplane fighter");
        fighterList.add("Fairey Pintail 2 seat floatplane fighter");
        fighterList.add("Farman HF.30 2 seat fighter");
        fighterList.add("Farman F.31 2 seat fighter");
        fighterList.add("FBA Ca2 Avion-Canon 2 seat fighter");
        fighterList.add("FFA P-16");
        fighterList.add("FFVS 22");
        fighterList.add("FMA I.Ae. 27 Pulqui I");
        fighterList.add("FMA I.Ae. 30 Ñancú");
        fighterList.add("FMA I.Ae. 33 Pulqui II");
        fighterList.add("Fiat CR.1/CR.2/CR.5/CR.10");
        fighterList.add("Fiat CR.20");
        fighterList.add("Fiat CR.25 heavy fighter");
        fighterList.add("Fiat CR.30");
        fighterList.add("Fiat CR.32/CR.33/CR.40/CR.41");
        fighterList.add("Fiat CR.42");
        fighterList.add("Fiat G.50");
        fighterList.add("Fiat G.55/G.56/G.59");
        fighterList.add("Fiat G.91 strike fighter");
        fighterList.add("Fisher P-75 Eagle");
        fighterList.add("Focke-Wulf Fw 57");
        fighterList.add("Focke-Wulf Fw 159");
        fighterList.add("Focke-Wulf Fw 187 heavy fighter");
        fighterList.add("Focke-Wulf Fw 190");
        fighterList.add("Focke-Wulf Ta 152");
        fighterList.add("Focke-Wulf Ta 154 night fighter");
        fighterList.add("Fokker D.I");
        fighterList.add("Fokker D.II");
        fighterList.add("Fokker D.III");
        fighterList.add("Fokker D.IV");
        fighterList.add("Fokker D.V");
        fighterList.add("Fokker D.VI");
        fighterList.add("Fokker D.VII & V.34 & 36");
        fighterList.add("Fokker D.IX/PW-6");
        fighterList.add("Fokker D.X");
        fighterList.add("Fokker D.XI/PW-7");
        fighterList.add("Fokker D.XII");
        fighterList.add("Fokker D.XIII");
        fighterList.add("Fokker D.XIV");
        fighterList.add("Fokker D.XVI");
        fighterList.add("Fokker D.XVII");
        fighterList.add("Fokker D.XXI");
        fighterList.add("Fokker D.XXIII");
        fighterList.add("Fokker DC.I");
        fighterList.add("Fokker Dr.I triplane");
        fighterList.add("Fokker E.I");
        fighterList.add("Fokker E.II");
        fighterList.add("Fokker E.III");
        fighterList.add("Fokker E.IV");
        fighterList.add("Fokker E.V/D.VIII");
        fighterList.add("Fokker G.I");
        fighterList.add("Fokker K.I twin engine 2 seat fighter");
        fighterList.add("Fokker M.16/B.III");
        fighterList.add("Fokker PW-5");
        fighterList.add("Fokker V.1");
        fighterList.add("Fokker V.2");
        fighterList.add("Fokker V.3");
        fighterList.add("Fokker V.4");
        fighterList.add("Fokker V.6 triplane");
        fighterList.add("Fokker V.7 triplane");
        fighterList.add("Fokker V.8 tandem triplane-biplane");
        fighterList.add("Fokker V.17, V.20, V.23 & V.25");
        fighterList.add("Fokker V.27 & V.37 inline E.V");
        fighterList.add("Folland Gnat");
        fighterList.add("Folland Midge light fighter");
        fighterList.add("Friedrichshafen FF.43");
        fighterList.add("Friedrichshafen FF.46");
        fighterList.add("Friedrichshafen FF.54 triplane/quadruplane");
        fighterList.add("FVM J 23");
        fighterList.add("FVM J 24");
        fighterList.add("Gabardini G.8");
        fighterList.add("Gabardini G.9");
        fighterList.add("Galvin HC floatplane fighter");
        fighterList.add("Geest Fighter");
        fighterList.add("General Aviation XFA");
        fighterList.add("General Dynamics F-16 Fighting Falcon");
        fighterList.add("General Dynamics F-16XL");
        fighterList.add("General Dynamics/Grumman F-111B");
        fighterList.add("Germania DB 2 seat fighter");
        fighterList.add("Germania JM");
        fighterList.add("Gloster E.1/44 jet fighter");
        fighterList.add("Gloster F.5/34");
        fighterList.add("Gloster F.9/37");
        fighterList.add("Gloster Gambet/Nakajima A1N");
        fighterList.add("Gloster Gamecock");
        fighterList.add("Gloster Gauntlet");
        fighterList.add("Gloster Gladiator & Sea Gladiator");
        fighterList.add("Gloster Gnatsnapper carrier fighter");
        fighterList.add("Gloster Goldfinch");
        fighterList.add("Gloster Gorcock");
        fighterList.add("Gloster Grebe");
        fighterList.add("Gloster Grouse");
        fighterList.add("Gloster Guan");
        fighterList.add("Gloster Javelin");
        fighterList.add("Gloster Mars, Nightjar & Sparrowhawk");
        fighterList.add("Gloster Meteor jet fighter");
        fighterList.add("Goodyear F2G Corsair");
        fighterList.add("Gorbunov 105");
        fighterList.add("Gourdou-Leseurre Type A");
        fighterList.add("Gourdou-Leseurre Type B, GL.2/21/22/23/24");
        fighterList.add("Gourdou-Leseurre GL.30 series");
        fighterList.add("Gourdou-Leseurre GL.40, 410 & 450");
        fighterList.add("Gourdou-Leseurre GL.50");
        fighterList.add("Gourdou-Leseurre GL.482");
        fighterList.add("Grigorovich I-1");
        fighterList.add("Grigorovich I-2 & I-2bis");
        fighterList.add("Grigorovich DI-3");
        fighterList.add("Grigorovich I-Z");
        fighterList.add("Grigorovich IP-1 cannon fighter");
        fighterList.add("Grigorovich IP-4 cannon fighter");
        fighterList.add("Grumman FF/G-5/G-23");
        fighterList.add("Grumman F2F");
        fighterList.add("Grumman F3F");
        fighterList.add("Grumman F4F Wildcat");
        fighterList.add("Grumman XF5F Skyrocket");
        fighterList.add("Grumman F6F Hellcat");
        fighterList.add("Grumman F7F Tigercat");
        fighterList.add("Grumman F8F Bearcat");
        fighterList.add("Grumman F9F Panther");
        fighterList.add("Grumman F-9 Cougar");
        fighterList.add("Grumman XF10F Jaguar");
        fighterList.add("Grumman F-11 Tiger");
        fighterList.add("Grumman F-14 Tomcat");
        fighterList.add("Grumman XP-50");
        fighterList.add("Grumman GG");
        fighterList.add("Grumman SF/G-6");
        fighterList.add("Gudkov GU-1");
        fighterList.add("Gudkov GU-82");
        fighterList.add("Häfeli DH-4");
        fighterList.add("HAL Ajeet");
        fighterList.add("HAL HF-24 Marut");
        fighterList.add("HAL Tejas");
        fighterList.add("Halberstadt D.I");
        fighterList.add("Halberstadt D.II - D.V");
        fighterList.add("Hall XFH");
        fighterList.add("Handley Page Type S");
        fighterList.add("Hannover CL.II escort fighter");
        fighterList.add("Hanriot HD.1");
        fighterList.add("Hanriot HD.2 floatplane fighter");
        fighterList.add("Hanriot HD.3");
        fighterList.add("Hanriot HD.5 2 seat fighter");
        fighterList.add("Hanriot HD.6 2 seat fighter");
        fighterList.add("Hanriot HD.7");
        fighterList.add("Hanriot HD.8 naval landplane fighter");
        fighterList.add("Hanriot HD.12 naval landplane fighter");
        fighterList.add("Hanriot HD.15 2 seat high altitude fighter");
        fighterList.add("Hanriot H.26");
        fighterList.add("Hanriot H.31");
        fighterList.add("Hanriot H.33");
        fighterList.add("Hanriot H.110 & H.115 pusher monoplane");
        fighterList.add("Hanriot H.220, H.220-2 & NC.600 heavy fighter");
        fighterList.add("Hansa-Brandenburg CC");
        fighterList.add("Hansa-Brandenburg D.I");
        fighterList.add("Hansa-Brandenburg KDW floatplane fighter");
        fighterList.add("Hansa-Brandenburg KF pusher fighter");
        fighterList.add("Hansa-Brandenburg L.14");
        fighterList.add("Hansa-Brandenburg L.16 triplane");
        fighterList.add("Hansa-Brandenburg W.11 floatplane fighter");
        fighterList.add("Hansa-Brandenburg W.12 floatplane fighter");
        fighterList.add("Hansa-Brandenburg W.16 floatplane fighter");
        fighterList.add("Hansa-Brandenburg W.17 flying boat fighter");
        fighterList.add("Hansa-Brandenburg W.18 flying boat fighter");
        fighterList.add("Hansa-Brandenburg W.19 floatplane fighter");
        fighterList.add("Hansa-Brandenburg W.25 floatplane fighter");
        fighterList.add("Hansa-Brandenburg W.27 floatplane fighter");
        fighterList.add("Hansa-Brandenburg W.29/W.33 floatplane fighter");
        fighterList.add("Hansa-Brandenburg W.32 floatplane fighter");
        fighterList.add("Hawker Demon");
        fighterList.add("Hawker F.20/27");
        fighterList.add("Hawker Fury");
        fighterList.add("Hawker Fury (monoplane)");
        fighterList.add("Hawker Hart Fighter");
        fighterList.add("Hawker Hawfinch");
        fighterList.add("Hawker Heron");
        fighterList.add("Hawker Hoopoe");
        fighterList.add("Hawker Hornbill");
        fighterList.add("Hawker Hotspur turret fighter");
        fighterList.add("Hawker Hunter");
        fighterList.add("Hawker Hurricane & Sea Hurricane");
        fighterList.add("Hawker Siddeley Kestrel FGA.1");
        fighterList.add("Hawker Nimrod biplane");
        fighterList.add("Hawker Osprey fleet fighter/reconnaissance");
        fighterList.add("Hawker P.1081 Australian Fighter");
        fighterList.add("Hawker P.V.3 day & night fighter");
        fighterList.add("Hawker Sea Fury");
        fighterList.add("Hawker Sea Hawk");
        fighterList.add("Hawker Tempest");
        fighterList.add("Hawker Tornado");
        fighterList.add("Hawker Typhoon");
        fighterList.add("Hawker Woodcock/Danecock/Dankok");
        fighterList.add("Heinkel HD 23");
        fighterList.add("Heinkel HD 37");
        fighterList.add("Heinkel HD 38");
        fighterList.add("Heinkel HD 43");
        fighterList.add("Heinkel He 49");
        fighterList.add("Heinkel He 51");
        fighterList.add("Heinkel He 74 light fighter");
        fighterList.add("Heinkel He 100/He 113");
        fighterList.add("Heinkel He 112");
        fighterList.add("Heinkel He 162 Volksjäger");
        fighterList.add("Heinkel He 219 night fighter");
        fighterList.add("Heinkel He 280");
        fighterList.add("Heinrich Pursuit");
        fighterList.add("Helwan HA-300");
        fighterList.add("Henschel Hs 124 heavy fighter");
        fighterList.add("HESA Azarakhsh");
        fighterList.add("HESA Saeqeh");
        fighterList.add("HESA Shafaq");
        fighterList.add("Hispano Aviación HA-1112");
        fighterList.add("Hispano Aviación Baron");
        fighterList.add("Horten Ho 229 jet flying wing");
        fighterList.add("Hughes D-2");
        fighterList.add("IAI Kfir");
        fighterList.add("IAI Lavi");
        fighterList.add("IAI Nammer");
        fighterList.add("IAI Nesher/Dagger");
        fighterList.add("IAR-11");
        fighterList.add("IAR-12");
        fighterList.add("IAR-13");
        fighterList.add("IAR-14");
        fighterList.add("IAR-15");
        fighterList.add("IAR-16");
        fighterList.add("IAR-80");
        fighterList.add("Ikarus IK-2");
        fighterList.add("Ikarus S-49");
        fighterList.add("Ilyushin I-21/TsKB-32");
        fighterList.add("Ilyushin Il-1");
        fighterList.add("Ilyushin Il-2I armoured fighter");
        fighterList.add("IMAM Ro.41");
        fighterList.add("IMAM Ro.44 floatplane fighter");
        fighterList.add("IMAM Ro.51");
        fighterList.add("IMAM Ro.57");
        fighterList.add("IMAM Ro.58");
        fighterList.add("IVL C.24");
        fighterList.add("IVL C.VI.25");
        fighterList.add("IVL Haukka");
        fighterList.add("Junkers CL.I");
        fighterList.add("Junkers J 2 all-metal monoplane fighter");
        fighterList.add("Junkers J 7 all-metal monoplane fighter");
        fighterList.add("Junkers J 9/D.I all-metal monoplane fighter");
        fighterList.add("Junkers T.22");
        fighterList.add("Junkers K 47");
        fighterList.add("Junkers Ju 88 night fighter");
        fighterList.add("Junkers Ju 388 night fighter");
        fighterList.add("KAI FA-50");
        fighterList.add("KAI KF-X");
        fighterList.add("Kasyanenko KPI-5");
        fighterList.add("Kawanishi N1K Kyofu floatplane fighter");
        fighterList.add("Kawanishi N1K-J Shiden landplane fighter");
        fighterList.add("Kawanishi K-11 carrier fighter");
        fighterList.add("Kawasaki KDA-3");
        fighterList.add("Kawasaki KDA-5 Army Type 92");
        fighterList.add("Kawasaki Ki-5");
        fighterList.add("Kawasaki Ki-10");
        fighterList.add("Kawasaki Ki-28");
        fighterList.add("Kawasaki Ki-45 heavy fighter");
        fighterList.add("Kawasaki Ki-60");
        fighterList.add("Kawasaki Ki-61");
        fighterList.add("Kawasaki Ki-64 heavy fighter");
        fighterList.add("Kawasaki Ki-96");
        fighterList.add("Kawasaki Ki-100");
        fighterList.add("Kawasaki Ki-102 & Ki-108");
        fighterList.add("Kochyerigin DI-6");
        fighterList.add("Kondor D.I");
        fighterList.add("Kondor D.II");
        fighterList.add("Kondor D.VI");
        fighterList.add("Kondor D.VII");
        fighterList.add("Koolhoven F.K.55");
        fighterList.add("Koolhoven F.K.58");
        fighterList.add("Kyushu J7W canard pusher");
        fighterList.add("Laville DI-4");
        fighterList.add("Lavochkin-Gorbunov-Gudkov LaGG-1");
        fighterList.add("Lavochkin-Gorbunov-Gudkov LaGG-3");
        fighterList.add("Lavochkin La-5");
        fighterList.add("Lavochkin La-7");
        fighterList.add("Lavochkin La-9");
        fighterList.add("Lavochkin La-11");
        fighterList.add("Lavochkin La-15");
        fighterList.add("Lavochkin La-126");
        fighterList.add("Lavochkin La-150");
        fighterList.add("Lavochkin La-152");
        fighterList.add("Lavochkin La-156");
        fighterList.add("Lavochkin La-160");
        fighterList.add("Lavochkin La-168");
        fighterList.add("Lavochkin La-176");
        fighterList.add("Lavochkin La-190");
        fighterList.add("Lavochkin La-200");
        fighterList.add("Lavochkin La-250");
        fighterList.add("Letov Š-3");
        fighterList.add("Letov Š-4");
        fighterList.add("Letov Š-7");
        fighterList.add("Letov Š-12");
        fighterList.add("Letov Š-13");
        fighterList.add("Letov Š-14");
        fighterList.add("Letov Š-20");
        fighterList.add("Letov Š-22");
        fighterList.add("Letov Š-31");
        fighterList.add("Letov Š-231");
        fighterList.add("Levasseur PL.5 shipborne fighter");
        fighterList.add("Levasseur PL.6 2 seat fighter");
        fighterList.add("Levy-Biche LB.2 & LB.6 naval fighter");
        fighterList.add("LFG Roland D.II");
        fighterList.add("LFG Roland D.III");
        fighterList.add("LFG Roland D.VI");
        fighterList.add("Lioré et Olivier LeO 7 bomber escort");
        fighterList.add("Liuchow Kwangsi Type 3");
        fighterList.add("Lloyd 40.15 triplane");
        fighterList.add("Lloyd 40.16");
        fighterList.add("Lockheed YP-24");
        fighterList.add("Lockheed P-38 Lightning");
        fighterList.add("Lockheed XP-49");
        fighterList.add("Lockheed XP-58 Chain Lightning");
        fighterList.add("Lockheed P-80 Shooting Star");
        fighterList.add("Lockheed XF-90");
        fighterList.add("Lockheed F-94/F-97 Starfire");
        fighterList.add("Lockheed F-104 Starfighter");
        fighterList.add("Lockheed YF-12");
        fighterList.add("Lockheed Martin F-22 Raptor");
        fighterList.add("Lockheed Martin F-35 Lightning II");
        fighterList.add("Lockheed XFV tail sitter");
        fighterList.add("Loening M-8");
        fighterList.add("Loening PA-1");
        fighterList.add("Loening PW-2");
        fighterList.add("Lohner 10.20 Spuckerl");
        fighterList.add("Lohner Type AA");
        fighterList.add("Lohner Type A/Dr.I");
        fighterList.add("Loire 43");
        fighterList.add("Loire 45");
        fighterList.add("Loire 46");
        fighterList.add("Loire 210 floatplane fighter");
        fighterList.add("Loire 250");
        fighterList.add("Loire-Nieuport LN.160, 161 & SNCAO 161");
        fighterList.add("Loring C-1");
        fighterList.add("LVG E.I");
        fighterList.add("LVG D 10");
        fighterList.add("LVG D.II");
        fighterList.add("LVG D.III");
        fighterList.add("LVG D.IV");
        fighterList.add("LVG D.V");
        fighterList.add("LVG D.VI");
        fighterList.add("Macchi C.200");
        fighterList.add("Macchi C.201");
        fighterList.add("Macchi C.202");
        fighterList.add("Macchi C.205");
        fighterList.add("Macchi M.5 flying boat fighter");
        fighterList.add("Macchi M.6 flying boat fighter");
        fighterList.add("Macchi M.7 flying boat fighter");
        fighterList.add("Macchi M.14");
        fighterList.add("Macchi M.26 flying boat fighter");
        fighterList.add("Macchi M.41 & M.41bis flying boat fighter");
        fighterList.add("Macchi M.71 catapult flying boat fighter");
        fighterList.add("Mann Egerton Type H ship-borne fighter");
        fighterList.add("Mann & Grimmer M.1 2 seat fighter");
        fighterList.add("etti MVT/SIAI S.50");
        fighterList.add("Marinens Flyvebaatfabrikk M.F.9");
        fighterList.add("Mark D.I");
        fighterList.add("Martin-Baker MB 2");
        fighterList.add("Martin-Baker MB 3");
        fighterList.add("Martin-Baker MB 5");
        fighterList.add("Martinsyde F.1");
        fighterList.add("Martinsyde Buzzard");
        fighterList.add("Martinsyde G.100");
        fighterList.add("MÁVAG Héja");
        fighterList.add("McDonnell XP-67");
        fighterList.add("McDonnell XF-85 Goblin parasite fighter");
        fighterList.add("McDonnell XF-88");
        fighterList.add("McDonnell F-101 Voodoo");
        fighterList.add("McDonnell Douglas AV-8B Harrier II Plus");
        fighterList.add("McDonnell Douglas F-15 Eagle");
        fighterList.add("McDonnell Douglas F-15E Strike Eagle");
        fighterList.add("McDonnell Douglas F/A-18 Hornet");
        fighterList.add("McDonnell FH Phantom");
        fighterList.add("McDonnell F2H Banshee");
        fighterList.add("McDonnell F3H Demon");
        fighterList.add("McDonnell Douglas F4H/F-110/F-4 Phantom II");
        fighterList.add("Messerschmitt Bf 109");
        fighterList.add("Messerschmitt Bf 110");
        fighterList.add("Messerschmitt Me 163 rocket fighter");
        fighterList.add("Messerschmitt Me 210");
        fighterList.add("Messerschmitt Me 262/Avia S-92");
        fighterList.add("Messerschmitt Me 263");
        fighterList.add("Messerschmitt Me 309");
        fighterList.add("Messerschmitt Me 310");
        fighterList.add("Messerschmitt Me 410");
        fighterList.add("Mikhelson/Korvin MK-1 Rybka floatplane/ski fighter");
        fighterList.add("Mikoyan-Gurevich I-210");
        fighterList.add("Mikoyan-Gurevich I-211");
        fighterList.add("Mikoyan-Gurevich I-220");
        fighterList.add("Mikoyan-Gurevich I-221");
        fighterList.add("Mikoyan-Gurevich I-222");
        fighterList.add("Mikoyan-Gurevich I-224");
        fighterList.add("Mikoyan-Gurevich I-225");
        fighterList.add("Mikoyan-Gurevich I-230");
        fighterList.add("Mikoyan-Gurevich I-231");
        fighterList.add("Mikoyan-Gurevich I-250 mixed power fighter");
        fighterList.add("Mikoyan-Gurevich I-70 & 270");
        fighterList.add("Mikoyan-Gurevich I-320");
        fighterList.add("Mikoyan-Gurevich I-370/I-1/I-2");
        fighterList.add("Mikoyan-Gurevich I-380/I-3");
        fighterList.add("Mikoyan-Gurevich I-75");
        fighterList.add("Mikoyan-Gurevich MiG-1");
        fighterList.add("Mikoyan-Gurevich MiG-3");
        fighterList.add("Mikoyan-Gurevich MiG-5/DIS");
        fighterList.add("Mikoyan-Gurevich MiG-7");
        fighterList.add("Mikoyan-Gurevich MiG-9");
        fighterList.add("Mikoyan-Gurevich MiG-15");
        fighterList.add("Mikoyan-Gurevich MiG-17");
        fighterList.add("Mikoyan-Gurevich MiG-19");
        fighterList.add("Mikoyan-Gurevich MiG-21");
        fighterList.add("Mikoyan-Gurevich MiG-21PD VTOL fighter");
        fighterList.add("Mikoyan-Gurevich MiG-23PD VTOL fighter");
        fighterList.add("Mikoyan-Gurevich MiG-23");
        fighterList.add("Mikoyan-Gurevich MiG-25");
        fighterList.add("Mikoyan MiG-29");
        fighterList.add("Mikoyan MiG-31");
        fighterList.add("Mikoyan MiG-35");
        fighterList.add("Mikoyan-Gurevich SM-12");
        fighterList.add("Mikoyan-Gurevich Ye-150 & Ye-152");
        fighterList.add("Mikoyan-Gurevich Ye-8");
        fighterList.add("Mikoyan Project 1.44");
        fighterList.add("Miles M.20");
        fighterList.add("Miles M.35 Libellula");
        fighterList.add("Miles Master Fighter");
        fighterList.add("Militär Apparat (Häfeli) MA-7");
        fighterList.add("Mitsubishi 1MF");
        fighterList.add("Mitsubishi 1MF2");
        fighterList.add("Mitsubishi 1MF9");
        fighterList.add("Mitsubishi 1MF10 7-shi carrier fighter");
        fighterList.add("Mitsubishi A5M");
        fighterList.add("Mitsubishi A6M Zero");
        fighterList.add("Mitsubishi A7M");
        fighterList.add("Mitsubishi ATD-X");
        fighterList.add("Mitsubishi F-1");
        fighterList.add("Mitsubishi F-2");
        fighterList.add("Mitsubishi G6M Heavy Fighter");
        fighterList.add("Mitsubishi J2M");
        fighterList.add("Mitsubishi J8M/Ki-200");
        fighterList.add("Mitsubishi Ka-8 two-seat shipboard fighter");
        fighterList.add("Mitsubishi Ki-18");
        fighterList.add("Mitsubishi Ki-33");
        fighterList.add("Mitsubishi Ki-46-III KAI Heavy Fighter (conversion)");
        fighterList.add("Mitsubishi Ki-83 heavy fighter");
        fighterList.add("Mitsubishi Ki-109 heavy day/night fighter");
        fighterList.add("Morane-Saulnier L/Pflaz E.III");
        fighterList.add("Morane-Saulnier N");
        fighterList.add("Morane-Saulnier I");
        fighterList.add("Morane-Saulnier V");
        fighterList.add("Morane-Saulnier AC");
        fighterList.add("Morane-Saulnier AF");
        fighterList.add("Morane-Saulnier AI");
        fighterList.add("Morane-Saulnier AN series");
        fighterList.add("Morane-Saulnier M.S.121");
        fighterList.add("Morane-Saulnier M.S.225");
        fighterList.add("Morane-Saulnier M.S.325");
        fighterList.add("Morane-Saulnier M.S.405");
        fighterList.add("Morane-Saulnier M.S.406");
        fighterList.add("Morane-Saulnier M.S.410");
        fighterList.add("Mosca MB bis");
        fighterList.add("Moskalev SAM-13");
        fighterList.add("Nakajima A2N");
        fighterList.add("Nakajima A4N");
        fighterList.add("Nakajima A6M2-N floatplane fighter");
        fighterList.add("Nakajima Army Type 91 Fighter");
        fighterList.add("Nakajima C6N-1S night fighter");
        fighterList.add("Nakajima J1N night fighter");
        fighterList.add("Nakajima J5N");
        fighterList.add("Nakajima Ki-8");
        fighterList.add("Nakajima Ki-11");
        fighterList.add("Nakajima Ki-12 & PE");
        fighterList.add("Nakajima Ki-27");
        fighterList.add("Nakajima Ki-43 Hayabusa");
        fighterList.add("Nakajima Ki-44 Shoki");
        fighterList.add("Nakajima Ki-58 heavy escort fighter");
        fighterList.add("Nakajima Ki-84 Hayate");
        fighterList.add("Nakajima Ki-87");
        fighterList.add("Nakajima Ki-116");
        fighterList.add("Nakajima Kikka");
        fighterList.add("Nakajima NAF-1 6-shi 2 seat carrier fighter");
        fighterList.add("Nakajima NAF-2 8-shi 2 seat carrier fighter");
        fighterList.add("Nanchang J-12");
        fighterList.add("Nielsen & Winther Type AA");
        fighterList.add("Nieuport 10");
        fighterList.add("Nieuport 11 & 16");
        fighterList.add("Nieuport 17, 21 & 23");
        fighterList.add("Nieuport 17bis, 24, 24bis, 25 & 27");
        fighterList.add("Nieuport 28");
        fighterList.add("Nieuport-Delage NiD 29");
        fighterList.add("Nieuport Nie 31RH");
        fighterList.add("Nieuport-Delage NiD 32RH lightweight naval fighter");
        fighterList.add("Nieuport-Delage NiD 37 high altitude fighter");
        fighterList.add("Nieuport-Delage NiD 40 high altitude fighter");
        fighterList.add("Nieuport-Delage NiD 42");
        fighterList.add("Nieuport-Delage NiD 43 2 seat floatplane fighter");
        fighterList.add("Nieuport-Delage NiD 48, 48bis & 481 lightweight fighter");
        fighterList.add("Nieuport-Delage NiD 52");
        fighterList.add("Nieuport-Delage NiD 62");
        fighterList.add("Nieuport-Delage NiD 622");
        fighterList.add("Nieuport-Delage NiD 626 Peruvian version");
        fighterList.add("Nieuport-Delage NiD 628 high altitude fighter");
        fighterList.add("Nieuport-Delage NiD 629");
        fighterList.add("Nieuport-Delage NiD 72");
        fighterList.add("Nieuport-Delage NiD 82");
        fighterList.add("Nieuport-Delage NiD 120 - NiD 125");
        fighterList.add("Nieuport Nighthawk\\Gloster Nighthawk");
        fighterList.add("Nikitin-Shevchenko IS polymorphic fighter");
        fighterList.add("North American NA-50 & P-64");
        fighterList.add("North American P-51 Mustang");
        fighterList.add("North American P-82/F-82 Twin Mustang");
        fighterList.add("North American/Canadair/CAC F-86 Sabre");
        fighterList.add("North American FJ-1 Fury");
        fighterList.add("North American FJ-2/-3 Fury");
        fighterList.add("North American FJ-4 Fury");
        fighterList.add("North American YF-93");
        fighterList.add("North American F-100 Super Sabre");
        fighterList.add("North American F-107");
        fighterList.add("Northrop XFT");
        fighterList.add("Northrop XP-56 Black Bullet");
        fighterList.add("Northrop P-61 Black Widow");
        fighterList.add("Northrop XP-79");
        fighterList.add("Northrop F-89 Scorpion");
        fighterList.add("Northrop F-5");
        fighterList.add("Northrop YF-17");
        fighterList.add("Northrop F-20 Tigershark");
        fighterList.add("Northrop YF-23");
        fighterList.add("NVI F.K.31");
        fighterList.add("Oeffag D.III");
        fighterList.add("Orenco B");
        fighterList.add("Orenco D");
        fighterList.add("Packard-Le Peré LUSAC-11 & LUSAC-21");
        fighterList.add("Panavia Tornado ADV");
        fighterList.add("Parnall Pipit");
        fighterList.add("Parnall Plover");
        fighterList.add("Parnall Puffin amphibious fighter");
        fighterList.add("Parnall Scout Zeppelin fighter");
        fighterList.add("Pashinin I-21");
        fighterList.add("Pemberton-Billing P.B.9");
        fighterList.add("Pemberton-Billing Nighthawk Zeppelin fighter");
        fighterList.add("Petlyakov Pe-3 night fighter");
        fighterList.add("Petlyakov VI-100 high altitude fighter");
        fighterList.add("Pfalz D.III");
        fighterList.add("Pfalz D.IV");
        fighterList.add("Pfalz D.VI");
        fighterList.add("Pfalz D.VII");
        fighterList.add("Pfalz D.VIII");
        fighterList.add("Pfalz D.XII");
        fighterList.add("Pfalz D.XIII");
        fighterList.add("Pfalz D.XIV");
        fighterList.add("Pfalz D.XV");
        fighterList.add("Pfalz Dr.I triplane");
        fighterList.add("Pfalz Dr.II triplane");
        fighterList.add("Pfalz E.I monoplane");
        fighterList.add("Pfalz E.II monoplane");
        fighterList.add("Pfalz E.IV monoplane");
        fighterList.add("Pfalz E.V monoplane");
        fighterList.add("Phönix 20.16 2 seat fighter");
        fighterList.add("Phönix 20.14, 20.15, D.I, D.II & D.III");
        fighterList.add("Phönix 20.22-25");
        fighterList.add("Piaggio P.2");
        fighterList.add("Piaggio P.119");
        fighterList.add("Polikarpov DI-1 two seat fighter");
        fighterList.add("Polikarpov I-1");
        fighterList.add("Polikarpov I-3");
        fighterList.add("Polikarpov I-5");
        fighterList.add("Polikarpov I-15");
        fighterList.add("Polikarpov I-15bis");
        fighterList.add("Polikarpov I-152");
        fighterList.add("Polikarpov I-153");
        fighterList.add("Polikarpov I-16");
        fighterList.add("Polikarpov I-17");
        fighterList.add("Polikarpov I-180");
        fighterList.add("Polikarpov I-185");
        fighterList.add("Polikarpov I-190");
        fighterList.add("Polikarpov ITP");
        fighterList.add("Polikarpov TIS heavy fighter");
        fighterList.add("Pomilio FVL-8");
        fighterList.add("Pomilio Gamma");
        fighterList.add("Ponnier M-1");
        fighterList.add("Port Victoria P.V.1 floatplane fighter");
        fighterList.add("Port Victoria P.V.2 & P.V.2bis floatplane fighter");
        fighterList.add("Port Victoria P.V.5 floatplane fighter");
        fighterList.add("Port Victoria P.V.5a floatplane fighter");
        fighterList.add("Port Victoria P.V.7 lightweight fighter");
        fighterList.add("Port Victoria P.V.8 lightweight fighter");
        fighterList.add("Port Victoria P.V.9 floatplane fighter");
        fighterList.add("Potez XI");
        fighterList.add("Potez 23");
        fighterList.add("Potez 26");
        fighterList.add("Potez 31 2 seat night fighter");
        fighterList.add("Potez 630");
        fighterList.add("Prajadhipok");
        fighterList.add("Praga E-44");
        fighterList.add("Praga E-45");
        fighterList.add("Podlaska Wytwórnia Samolotów PWS-1 & 1bis two-seat fighter");
        fighterList.add("Podlaska Wytwórnia Samolotów PWS-10");
        fighterList.add("PZL P.1");
        fighterList.add("PZL P.6");
        fighterList.add("PZL P.7");
        fighterList.add("PZL P.8");
        fighterList.add("PZL P.11");
        fighterList.add("PZL P.24");
        fighterList.add("PZL.38 Wilk heavy fighter");
        fighterList.add("PZL.50 Jastrząb");
        fighterList.add("Qaher-313");
        fighterList.add("Reggiane Re.2000");
        fighterList.add("Reggiane Re.2001");
        fighterList.add("Reggiane Re.2002");
        fighterList.add("Reggiane Re.2004");
        fighterList.add("Reggiane Re.2005");
        fighterList.add("Renard Epervier");
        fighterList.add("Renard R.36, R.37 & R.38");
        fighterList.add("R.E.P. C.1");
        fighterList.add("Republic AP-9");
        fighterList.add("Republic P-43 Lancer");
        fighterList.add("Republic P-47 Thunderbolt");
        fighterList.add("Republic XP-72");
        fighterList.add("Republic F-84 Thunderjet");
        fighterList.add("Republic XF-96/F-84F Thunderstreak");
        fighterList.add("Republic XF-91 Thunderceptor");
        fighterList.add("Republic F-105 Thunderchief");
        fighterList.add("Rex D (1917)");
        fighterList.add("Rikugun Ki-93 heavy fighter");
        fighterList.add("Rockwell XFV-12");
        fighterList.add("Rogožarski IK-3");
        fighterList.add("Romano R-110 3 seat fighter");
        fighterList.add("Roussel R.30");
        fighterList.add("Royal Aircraft Factory B.E.12 night fighter");
        fighterList.add("Royal Aircraft Factory F.E.8");
        fighterList.add("Royal Aircraft Factory N.E.1 night fighter");
        fighterList.add("Royal Aircraft Factory S.E.2");
        fighterList.add("Royal Aircraft Factory S.E.4");
        fighterList.add("Royal Aircraft Factory S.E.4a");
        fighterList.add("Royal Aircraft Factory S.E.5 & 5a");
        fighterList.add("Rumpler 6B Floatplane fighter");
        fighterList.add("Rumpler D.I");
        fighterList.add("Ryan FR Fireball mixed propulsion fighter");
        fighterList.add("Ryan XF2R Dark Shark mixed propulsion fighter");
        fighterList.add("Saab 21 pusher fighter");
        fighterList.add("Saab 21R jet fighter");
        fighterList.add("Saab 29 Tunnan");
        fighterList.add("Saab 32 Lansen");
        fighterList.add("Saab 35 Draken");
        fighterList.add("Saab 37 Viggen");
        fighterList.add("Saab JAS 39 Gripen");
        fighterList.add("Saunders A.10");
        fighterList.add("Saunders-Roe SR.A/1 seaplane jet fighter");
        fighterList.add("Saunders-Roe SR.53 rocket/jet interceptor");
        fighterList.add("Savoia-etti SM.88");
        fighterList.add("Savoia-etti SM.91");
        fighterList.add("Savoia-etti SM.92");
        fighterList.add("Schütte-Lanz D.I");
        fighterList.add("Schütte-Lanz D.II");
        fighterList.add("Schütte-Lanz D.III");
        fighterList.add("Schütte-Lanz D.IV");
        fighterList.add("SEA IV");
        fighterList.add("SET XV");
        fighterList.add("Seversky P-35");
        fighterList.add("Seversky XP-41");
        fighterList.add("Shchetinin (Grigorovich) M-11 & M-12 flying boat fighter");
        fighterList.add("Shenyang J-5");
        fighterList.add("Shenyang J-6");
        fighterList.add("Shenyang J-8 & J-8II");
        fighterList.add("Shenyang J-11");
        fighterList.add("Shenyang J-15");
        fighterList.add("Shenyang J-31");
        fighterList.add("Short Gurnard");
        fighterList.add("SIAI S.52");
        fighterList.add("SIAI S.58 seaplane fighter");
        fighterList.add("SIAI S.67 seaplane fighter");
        fighterList.add("Siemens-Schuckert D.I");
        fighterList.add("Siemens-Schuckert D.II");
        fighterList.add("Siemens-Schuckert D.III");
        fighterList.add("Siemens-Schuckert D.IV");
        fighterList.add("Siemens-Schuckert D.V");
        fighterList.add("Siemens-Schuckert D.VI parasol monoplane");
        fighterList.add("Siemens-Schuckert DDr.I twin engine push-pull fighter");
        fighterList.add("Siemens-Schuckert E.I, E.II & E.III");
        fighterList.add("Sikorsky S-16");
        fighterList.add("Sikorsky S-18 4-engine escort fighter");
        fighterList.add("Sikorsky S-20");
        fighterList.add("SNCAC (Centre) NC.1080 carrier fighter");
        fighterList.add("SNCAN (Nord) N.2200 carrier fighter");
        fighterList.add("SNCAO (Ouest) CAO.200");
        fighterList.add("SNCASO (Sud Aviation) Vautour II interceptor");
        fighterList.add("SNCASE (Sud-Est) Aquilon license-built DH Sea Venom");
        fighterList.add("SNCASE (Sud-Est) SE.100");
        fighterList.add("SNCASE (Sud-Est) Durandal");
        fighterList.add("SNCASO (Sud-Ouest) Espadon");
        fighterList.add("SNCASO (Sud-Ouest) Trident");
        fighterList.add("Sopwith Baby floatplane fighter");
        fighterList.add("Sopwith Bulldog two-seat fighter");
        fighterList.add("Sopwith Buffalo Armoured reconnaissance fighter");
        fighterList.add("Sopwith Camel");
        fighterList.add("Sopwith Dolphin");
        fighterList.add("Sopwith Dragon");
        fighterList.add("Sopwith Gunbus");
        fighterList.add("Sopwith 3F.2 Hippo two-seat fighter");
        fighterList.add("Sopwith Hispano-Suiza Triplane");
        fighterList.add("Sopwith 1½ Strutter");
        fighterList.add("Sopwith L.R.T.Tr. triplane escort fighter");
        fighterList.add("Sopwith Pup");
        fighterList.add("Sopwith Schneider");
        fighterList.add("Sopwith Snail");
        fighterList.add("Sopwith Snapper");
        fighterList.add("Sopwith Snark");
        fighterList.add("Sopwith Snipe");
        fighterList.add("Sopwith Swallow");
        fighterList.add("Sopwith Triplane");
        fighterList.add("SPAD SA.1-4 & SG");
        fighterList.add("SPAD S.VII");
        fighterList.add("SPAD S.XI Cn2 2 seat night fighter");
        fighterList.add("SPAD S.XII cannon fighter");
        fighterList.add("SPAD S.XIII");
        fighterList.add("SPAD S.XIV seaplane fighter");
        fighterList.add("SPAD S.XV");
        fighterList.add("SPAD S.XVII");
        fighterList.add("SPAD S.XX");
        fighterList.add("SPAD S.XXI");
        fighterList.add("SPAD S.XXII");
        fighterList.add("SPAD S.XXIV ships fighter");
        fighterList.add("Spyker-Trompenburg V.3");
        fighterList.add("Standard E-1");
        fighterList.add("Sturtevant B speed scout/pursuit");
        fighterList.add("Sukhoi Su-1 & Su-3 high altitude fighter");
        fighterList.add("Sukhoi Su-5 mixed power fighter");
        fighterList.add("Sukhoi Su-7 (1944)");
        fighterList.add("Sukhoi Su-9 (1946)");
        fighterList.add("Sukhoi Su-11 (1947)");
        fighterList.add("Sukhoi Su-15 (1949)");
        fighterList.add("Sukhoi Su-7");
        fighterList.add("Sukhoi T-3");
        fighterList.add("Sukhoi P-1");
        fighterList.add("Sukhoi Su-9");
        fighterList.add("Sukhoi Su-11");
        fighterList.add("Sukhoi Su-15");
        fighterList.add("Sukhoi Su-17, 20 & 22");
        fighterList.add("Sukhoi Su-27");
        fighterList.add("Sukhoi Su-30");
        fighterList.add("Sukhoi Su-32/Su-34");
        fighterList.add("Sukhoi Su-33");
        fighterList.add("Sukhoi Su-27M/Su-35");
        fighterList.add("Sukhoi Su-37");
        fighterList.add("Sukhoi Su-47");
        fighterList.add("Sukhoi PAK FA/HAL FGFA");
        fighterList.add("Supermarine 224 F.7/30");
        fighterList.add("Supermarine 508");
        fighterList.add("Supermarine 510");
        fighterList.add("Supermarine 525");
        fighterList.add("Supermarine 528");
        fighterList.add("Supermarine 529");
        fighterList.add("Supermarine 535");
        fighterList.add("Supermarine Attacker");
        fighterList.add("Supermarine Scimitar");
        fighterList.add("Supermarine Seafang");
        fighterList.add("Supermarine Seafire");
        fighterList.add("Supermarine Sea King seaplane fighter");
        fighterList.add("Supermarine Spitfire");
        fighterList.add("Supermarine Spiteful");
        fighterList.add("Supermarine Swift");
        fighterList.add("Svenska Aero Jaktfalken I & II");
        fighterList.add("Tachikawa Ki-106");
        fighterList.add("Tairov Ta-1 escort fighter");
        fighterList.add("Tairov Ta-3 escort fighter");
        fighterList.add("Tebaldi-Zari");
        fighterList.add("Tereshchenko No 7");
        fighterList.add("Thomas-Morse MB-1");
        fighterList.add("Thomas-Morse MB-2");
        fighterList.add("Thomas-Morse MB-3");
        fighterList.add("Thomas-Morse MB-9");
        fighterList.add("Thomas-Morse XP-13");
        fighterList.add("Thomas Morse TM-23");
        fighterList.add("Thulin K");
        fighterList.add("TNCA Series C Microplano");
        fighterList.add("TNCA Series E Tololoche");
        fighterList.add("Tokorozawa Koshiki-2");
        fighterList.add("Tomasevic I-110 heavy fighter");
        fighterList.add("Tupolev ANT-5/I-4");
        fighterList.add("Tupolev ANT-13/I-8");
        fighterList.add("Tupolev ANT-21");
        fighterList.add("Tupolev ANT-23/I-12");
        fighterList.add("Tupolev ANT-29 cannon fighter");
        fighterList.add("Tupolev ANT-31/I-14");
        fighterList.add("Tupolev ANT-46/DI-8 heavy cannon fighter");
        fighterList.add("Tupolev Tu-1 night fighter");
        fighterList.add("Tupolev Tu-28/Tu-128");
        fighterList.add("TuAF TFX");
        fighterList.add("VEF I-16");
        fighterList.add("VFW VAK 191B VTOL fighter");
        fighterList.add("VL Humu");
        fighterList.add("VL Mörkö-Morane");
        fighterList.add("VL Myrsky");
        fighterList.add("VL Pyörremyrsky");
        fighterList.add("Vickers E.F.B.1");
        fighterList.add("Vickers E.F.B.2");
        fighterList.add("Vickers E.F.B.3");
        fighterList.add("Vickers F.B.5");
        fighterList.add("Vickers E.F.B.7 twin engine fighter");
        fighterList.add("Vickers E.F.B.8 twin engine fighter");
        fighterList.add("Vickers F.B.9");
        fighterList.add("Vickers F.B.11 3 seat escort fighter");
        fighterList.add("Vickers F.B.12");
        fighterList.add("Vickers F.B.16");
        fighterList.add("Vickers F.B.19");
        fighterList.add("Vickers F.B.24 2 seat fighter");
        fighterList.add("Vickers F.B.25 night fighter");
        fighterList.add("Vickers E.S.1");
        fighterList.add("Vickers Jockey");
        fighterList.add("Vickers Type 123 & 141");
        fighterList.add("Vickers Type 143 Bolivian Scout");
        fighterList.add("Vickers Type 161");
        fighterList.add("Vickers Type 177 shipboard fighter");
        fighterList.add("Vickers Type 432");
        fighterList.add("Vickers Vampire");
        fighterList.add("Vickers Venom");
        fighterList.add("Vickers Vireo");
        fighterList.add("Villiers II 2 seat carrier fighter");
        fighterList.add("Villiers V night fighter");
        fighterList.add("Villiers 8 single seat carrier fighter");
        fighterList.add("Villiers 24 night fighter");
        fighterList.add("Vought VE-7S & VE-7SF");
        fighterList.add("Vought VE-8");
        fighterList.add("Vought VE-9");
        fighterList.add("Vought V-80");
        fighterList.add("Vought V-141/V-143");
        fighterList.add("Vought FU");
        fighterList.add("Vought XF2U");
        fighterList.add("Vought XF3U");
        fighterList.add("Vought F4U/FG/F3A Corsair");
        fighterList.add("Vought XF5U");
        fighterList.add("Vought F6U Pirate");
        fighterList.add("Vought F7U Cutlass");
        fighterList.add("Vought F8U/F-8 Crusader");
        fighterList.add("Vought XF8U-3 Crusader III");
        fighterList.add("Vultee XP-54");
        fighterList.add("Vultee P-66 Vanguard");
        fighterList.add("Waco CSO-A/240A");
        fighterList.add("Waco CTO-A");
        fighterList.add("Weiss Manfred WM-23");
        fighterList.add("Westland C.O.W. Gun Fighter");
        fighterList.add("Westland F.7/30");
        fighterList.add("Westland Interceptor");
        fighterList.add("Westland N.1B floatplane fighter");
        fighterList.add("Westland Wagtail");
        fighterList.add("Westland Weasel");
        fighterList.add("Westland Welkin high altitude interceptor");
        fighterList.add("Westland Westbury home defence fighter");
        fighterList.add("Westland Whirlwind");
        fighterList.add("Westland Wizard");
        fighterList.add("Westland Wyvern torpedo/strike fighter");
        fighterList.add("Weymann W-1");
        fighterList.add("Wibault 1");
        fighterList.add("Wibault 3");
        fighterList.add("Wibault 7 & Vickers Wibault");
        fighterList.add("Wibault 8 Simoun");
        fighterList.add("Wibault 9");
        fighterList.add("Wibault 12, 121 & 122 Sirocco");
        fighterList.add("Wibault 130 Trombe & 170 Tornade lightweight fighter");
        fighterList.add("Wibault 210");
        fighterList.add("Wibault 313");
        fighterList.add("Wight Baby floatplane fighter");
        fighterList.add("Wight Quadruplane");
        fighterList.add("WKF D.I");
        fighterList.add("WKF Dr.I");
        fighterList.add("Wright XF3W");
        fighterList.add("Xian JH-7");
        fighterList.add("Yakovlev I-29");
        fighterList.add("Yakovlev Yak-1");
        fighterList.add("Yakovlev I-30/Yak-3");
        fighterList.add("Yakovlev Yak-7");
        fighterList.add("Yakovlev Yak-9");
        fighterList.add("Yakovlev Yak-15");
        fighterList.add("Yakovlev Yak-17");
        fighterList.add("Yakovlev Yak-19");
        fighterList.add("Yakovlev Yak-23");
        fighterList.add("Yakovlev Yak-25 (1947)");
        fighterList.add("Yakovlev Yak-25 interceptor");
        fighterList.add("Yakovlev Yak-27V/K interceptor");
        fighterList.add("Yakovlev Yak-28P interceptor");
        fighterList.add("Yakovlev Yak-30 (1948)");
        fighterList.add("Yakovlev Yak-36 VTOL fighter");
        fighterList.add("Yakovlev Yak-38 VTOL fighter");
        fighterList.add("Yakovlev Yak-41/141");
        fighterList.add("Yakovlev Yak-50 (1949)");
        fighterList.add("Yatsenko I-28");
        fighterList.add("Yokosuka D4Y2-S heavy night fighter");
        fighterList.add("Yokosuka P1Y2 Kyokko night fighter");
        fighterList.add("Zeppelin-Lindau (Dornier) D.I");
        
		ArrayAdapter<String> dataAdapter = new ArrayAdapter<String>(this, R.layout.figherjetstextview, fighterList);
		setListAdapter(dataAdapter);
		ListView listView = getListView();
		// enables filtering for the contents of the given ListView
		listView.setTextFilterEnabled(true);
		listView.setOnItemClickListener(new OnItemClickListener() {
			public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
				//////Log.w(TAG, "In Flight.displayListView().listView.setOnItemClickListener().onItemClick()");
				//com.jimsuplee.aircraftcarriers.Aircraftcarriers.carrierSearchList.clear();
				Intent i = new Intent("");
				String fighterChoice = ((TextView) view).getText().toString();			
				i.setData(Uri.parse(fighterChoice));
				setResult(RESULT_OK, i);
				finish();
			}
		});    
    }
}
